@startuml
participant UnitTest<< (T,#ADD1B2) >>
participant Response<< (M,#B2D1AD) >>
participant Request<< (M,#B2D1AD) >>
participant "UpdateBuilding\n(Subject Under Test)" as UpdateBuilding 
participant DomainFacade<< (M,#B2D1AD) >>
UnitTest -> Request: setParameter("action")
UnitTest -> Request: setParameter("id")
UnitTest -> Request: setParameter("...")
create UpdateBuilding
UnitTest -> UpdateBuilding: processRequest( req, resp)
UpdateBuilding -> Request: getParameter("action")
group get parameters and make building object
UpdateBuilding -> Request: getParameter("id")
note over Request, UpdateBuilding
    pick out other paramters and make building object
end note 
end
UpdateBuilding -> DomainFacade: updateBuilding( b )

Response <- UpdateBuilding: redirect to buildings.jsp

UnitTest -> UnitTest: Verify the building created

@enduml
