@startuml
Browser -> Tomcat: req: post form
create Request
Tomcat -> Request: setParameters
create UpdateBuilding
Tomcat -> UpdateBuilding: processRequest( req, resp)
UpdateBuilding -> Request: getParameter("action")
group get parameters and make building object
UpdateBuilding -> Request: getParameter("id")
note over Request, UpdateBuilding
    pick out other paramters and make building object
end note
end
UpdateBuilding -> DomainFacade: updateBuilding( b )
DomainFacade -> DBFacade: updateBuilding( b )
group implementation of getBuildings()
    |||
    create JDBCConnection
    DBFacade -> JDBCConnection : getConnection() 
    create JDBCStatement
    DBFacade -> JDBCStatement
    note over DBFacade, JDBCConnection
        using connection and statement
    end note
end
DomainFacade <- DBFacade: return List
UpdateBuilding <- DomainFacade: return List
Tomcat <- UpdateBuilding: redirect to buildings.jsp
Tomcat -> buildings.jsp: "build page"

buildings.jsp -> DomainFacade: getBuildings()
DomainFacade -> DBFacade: getBuildings()
group implementation of getBuildings()
    |||
    create JDBCConnection
    DBFacade -> JDBCConnection : getConnection() 
    create JDBCStatement
    DBFacade -> JDBCStatement
    note over DBFacade, JDBCConnection
        using connection and statement
    end note
end
DomainFacade <- DBFacade: return List
buildings.jsp <- DomainFacade: return List
Tomcat <- buildings.jsp: HTML document
Browser <- Tomcat: HTML document
@enduml
