@startuml
participant UnitTest << (T,#ADD1B2) >>
participant DBFacade
participant JDBCConnection << (T,#ADD1B2) >>
participant JDBCStatement
create JDBCConnection
UnitTest -> JDBCConnection: get testConnection
UnitTest <-- JDBCConnection: connection
Create DBFacade
UnitTest -> DBFacade: setConnection( testConnection s)
UnitTest -> DBFacade: getBuildings()
group implementation of getBuildings()
|||
DBFacade -> JDBCConnection
create JDBCStatement
DBFacade -> JDBCStatement
end
UnitTest <- DBFacade: return List<Building>
UnitTest <- UnitTest: assert list has 5 elements
@enduml