@startuml
Browser -> Tomcat: req: buildings.jsp
Tomcat -> buildings.jsp: "build page"

buildings.jsp -> DomainFacade: getBuildings()
DomainFacade -> DBFacade: getBuildings()
group implementation of getBuildings()
    |||
    create JDBCConnection
    DBFacade -> JDBCConnection : getConnection() 
    create JDBCStatement
    DBFacade -> JDBCStatement
    note over DBFacade, JDBCConnection
        using connection and statement
    end note
end
DomainFacade <- DBFacade: return List
buildings.jsp <- DomainFacade: return List
Tomcat <- buildings.jsp: HTML document
Browser <- Tomcat: HTML document
@enduml
